services:
  booksarr:
    build: .
    container_name: booksarr
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - HARDCOVER_API_KEY=
      - GOOGLE_BOOKS_API_KEY=    # Optional but recommended: for accurate publish dates (free)
      - DOWNLOADS_DIR=/downloads
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - /Users/jsg/Local Projects/sample_ebook:/books
    ports:
      - 8889:8889
    restart: unless-stopped
